### PR TITLE
dependency injection for models and evaluators

### PR DESCRIPTION
**Pull request by LazaroHurtado**
I plan on adding some more model support to this repo but I wanted to first break the code up to add some abstraction behind using a model and an evaluator. Only after making these changes did I realize that there is an existing PR doing something similar, although this work takes a different approach and adds some extra features as detailed below:
- **Dependency injection over inheritance**: Rather than making the OpenAI and Anthropic models inherit `LLMNeedleHaystackTester` I decided to use dependency injection since those models should be unaware of the test, and thus introducing some encapsulation around it.
- **Evaluator class**: I added an evaluator abstract class to make it easier for developers to run tests with different evaluator models. This model gets passed to the tester through dependency injection.
- **Makefile**: Added a makefile to make running this project a tad bit easier for devs.
- **Command args**: Setup some command line args for ease of use.

I do not have neither a OpenAI nor Anthropic api key so would appreciate someone who does to confirm the changes does not introduce any bugs

### CODE REVIEW

**Comment by gkamradt** [comment]
Hey Lazaro! just wanted to give an update from my end - I'm so stoked about the energy around this PR. Thank you very much for the clean work around it.

I recently posted a [tweet](https://twitter.com/GregKamradt/status/1762178200569057308) for a co-maintainer on this project so we can take it to the next level.

Expect a note from me within the next week on next steps.

Progress will be made!

**Comment by kedarchandrayan** [comment]
Hi @LazaroHurtado, Kedar here, one of the co-maintainers. Greatly appreciate the separation of model interactions and evaluations. Liked it!

Here are my review comments:
**Comment 1**: Multiple `langsmith` versions are used in requirements.txt

**Comment 2**: I suggest using default venv name - `venv`

**Comment 3**: Please consider "Inference" in place of "Tester" as a naming convention. I think tester is a far wide name for this case. Following folder structure is what I propose:

```
models
    - __init__.py
    - inference_base.py
    - anthropic_inference.py
    - openai_inference.py
```

There will be related changes regarding comment 3 in other places too.

**Comment by kedarchandrayan** [comment]
Continuing the review comments (cc: @LazaroHurtado )

**Comment 4**: It's important to thoroughly document all the command line arguments accepted by `main.py` for clarity and ease of use. Currently, only the `provider` argument is documented in the README.

For example, the script can be invoked with the following command:

```
python main.py --provider openai --evaluator openai --api_key YOUR_OPENAI_API_KEY --evaluator_api_key YOUR_EVALUATOR_API_KEY
```

**Comment by kedarchandrayan** [comment]
Continuing the review comments (cc: @LazaroHurtado )

**Comment 4**: It's important to thoroughly document all the command line arguments accepted by `main.py` for clarity and ease of use. Currently, only the `provider` argument is documented in the README.

For example, the script can be invoked with the following command:

```
python main.py --provider openai --evaluator openai --api_key YOUR_OPENAI_API_KEY --evaluator_api_key YOUR_EVALUATOR_API_KEY
```

**Comment by LazaroHurtado** [comment]
@kedarchandrayan thank you for taking the time to preview my PR. I have implemented all your suggestions.

I think I also saw a comment discussing the `Tester` suffix for the models classes, I agree that this was a bad naming choice. I have changed the `models` folder to `providers` so each model that inherits `ModelProvider` does not need any kinda of suffix; i.e. `OpenAI`, `Anthropic`, or `Google`. This also lead me to change the `__init__.py` in `src` so developers are forced to import those model classes by referencing the `providers` folder as can be seen in `main.py`

**Comment by kedarchandrayan** [comment]
Thanks @LazaroHurtado for the changes!
I withdrew the renaming of classes and files comment as it seemed too opinionated. It's great to know we share the same thoughts!

I have another review comment.

**Comment 4**: Since `main.py` is now the common entry point for developers who simply want to run the script, let's ensure all parameters for the `LLMNeedleHaystackTester` class are accessible via `main.py`.

To give an example, parameters like `needle`, `retrieval_question`, `context_lengths_min`, etc should be command line arguments for `main.py`.

**Comment by LazaroHurtado** [comment]
@kedarchandrayan I value and encourage all types of feedback, parameter names are tricky sometimes 😅

I added `LLMNeedleHaystackTester` parameters to the command line args. I still left the parameters and their default values in the tester class since the sole purpose of `main.py` is a quick and simple script for running the analysis and not a replacement for any type of logic found in the source code files (`src/*.py`)

**Comment by pavelkraleu** [comment]
Thank you for great work @LazaroHurtado!

Here are my notes from testing your code

Things which prevents running the test and should be fixed:
1. `model_name` in `OpenAIEvaluator` is set to `gpt4` which is not valid and OpenAI API rejects it
    - Consider using `gpt-4` instead
2. `context_lengths_max` is set to `200000` which is too much for any OpenAI model
    - This was probably left there from tests on Anthropic 
    - Consider lowering the value to 8k, compatible with GPT-4

If you agree, we can create Issues for things below and fix them at some point

Situation around `context_lengths_max` I mentioned above points me to:
- Maybe we should not have generic `OpenAI(ModelProvider)` but something like `GPT4_8k(ModelProvider)`
- I think OpenAI class is too generic for having only variable `model_name` because variables like context window are very important 
- Maybe we can start with only GPT-3.5 and not expensive GPT-4
- Variable  `context_lengths_max` is closely related to model used in Provider and Evaluator, maybe we have to rethink how this variable is used. 

Some other ideas:
- Consider using something like `#!/usr/bin/env python3` in `main.py`
- Two similar classes are named differently, consider removing `Evaluator` from `OpenAIEvaluator(Evaluator)`
    - `OpenAI(ModelProvider)` `OpenAIEvaluator(Evaluator)`
- Consider renaming file `evaluators/openai_evaluator.py` to `openai.py` to be in line with `providers/openai.py`

**Comment by LazaroHurtado** [comment]
@pavelkraleu thank you for taking the time to review my PR and running it as well. I will make the changes to the default model name and context length. I have some follow up questioned embedded in the following text that I would like some clarification before making all the fixes.

I agree that we should open issues or discussions for the points you mentioned.
- I like the idea of getting specific models prebuilt, which can be done through inheritance as you suggested or by the introduction of preset model configuration classes which are passed to the provider class through a static method -- 
```python3
OpenAI.from_config(GPT4Config(context_length=8000), api_key)
```
- Whichever approach we take for the above bullet point, it will most likely resolve your concern of context length. Although I should mention that the tester class should still have this argument in case the user does not want to test to the full context window. We can take the minimum between the argument and the model's max length, as well as printing a warning if the user surpassed the model's capacity.
- Are you suggestion making the default gpt-3.5? If so I can add that to this PR, I kept it as gpt4 so the default reproduces the originals results but dont mind changing.

For your other ideas:
- I added the shebang to allow users to run it as a script if the execution flag is enabled.
- I didn't want to have any confusion or require the user to use an alias when importing `OpenAI` from both providers and evaluators folders so I named one class different from the other. Thinking about it now maybe I should change the `OpenAI` class to `OpenAIProvider`. Thoughts?
- File renamed, thanks for catching that!

**Comment by kedarchandrayan** [comment]
Yup, agree with @pavelkraleu! Let's try to merge the PR quickly and take add the other changes, which are not related to the main theme of the PR, as different issues.

**Comment by LazaroHurtado** [comment]
@pavelkraleu @kedarchandrayan I made the changes so we default to `gpt-3.5-turbo-0125` with max context length of 16k as described by the oai docs

**Comment by pavelkraleu** [comment]
LGTM

**Pull request merged**
